### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by leehendo** [mesutpiskin/FaceDetectionAndRecognition#1]
Hi,
I managed to create the form and have it start but how do i get it to work as per your video?
Regards
Lee

**Comment by mesutpiskin** [comment]
Hi Lee,
if can you want to processing video, look at http://www.emgu.com/wiki/files/3.2.0/document/html/961857d0-b7ba-53d8-253a-5059bb3bc1df.htm

`VideoCapture("home/video.mp4")`
