### ISSUE TITLE
Browser webcam

### ISSUE THREAD

**Issue by mikesmithfreels** [mesutpiskin/FaceDetectionAndRecognition#10]
Thank you guys!!

I want to recognize face using browser's webcam, how to integrate that? Can you please let me know

**Comment by mesutpiskin** [comment]
Thanks! you can try opencv.js framework.

for example https://huningxin.github.io/opencv.js/samples/index.html

**Comment by mikesmithfreels** [comment]
Thanks for quick reply, 

will definitely try opencv framework
